### ISSUE TITLE
Why no requirements.txt?

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/Banana#2]
https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format

**Comment by JimJeon** [comment]
아 맞당 까묵음 ㅋㅋㅋㅋ

**Comment by juice500ml** [comment]
4bfd85ffa1d46cc1518d3d1beebb66378f67a3d9
커밋할때 이슈 번호 적으면 자동으로 citation 됩니당
ex) git commit -m "Add python package requirements (#2)"

**Comment by JimJeon** [comment]
팁 감사합니당~ :)
